name: Docs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

jobs:
  Deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Generate Docs
        run: ./.github/workflows/generate_docs.sh

      - name: Upload documentation zip archive
        uses: actions/upload-artifact@v4
        with:
          name: bluegps-sdk-android-docs
          path: android-docs/html

      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './android-docs/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Build Docker image
        run: docker build . --file android-docs/Dockerfile --tag bluegps-sdk-android-docs:latest

      - name: Tag image
        run: docker tag bluegps-sdk-android-docs:latest ghcr.io/synapseslab/android-bluegps-sdk-public/android-docs:latest

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: docker push ghcr.io/synapseslab/android-bluegps-sdk-public/android-docs:latest
